BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        id: button_clear
        on_press: app.clear()
    Button:
        text: 'two'
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        id: button_pressed
        on_press: app.pressed()
    Label:
        id: output_label
        text: 'Huy'
        color: (1, 1, 0, 1)